---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
source("/Users/henrique/Desktop/weoapp/visualizingWEOv2.R")
```

Column {.sidebar}
-----------------------------------------------------------------------

Test

```{r}
selectInput("ctry", label = "Country",
            choices = c("Denmark", "Finland", "Norway", "Sweden"), selected = "Norway")

```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A



```{r}
renderPlot({
  full_weo %>%
  filter(Country == as.character(input$Country) & year>2018 & year < 2024) %>%
  ggplot(aes(y=LUR, x=year, fill=Version)) +
  geom_bar(position="dodge", stat="identity") +
  labs(title="IMF WEO Denmark Unemployment Forecasts")
)}
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPlot({
full_weo %>%
  filter(Country == as.character(input$Country) & year>2018 & year < 2024) %>%
  ggplot(aes(y=NGDP_RPCH, x=year, fill=Version)) +
  geom_bar(position="dodge", stat="identity") +
  labs(title="IMF WEO Denmark GDP Growth Forecasts")
})
```

### Chart C

```{r}
renderPlot({
full_weo %>%
  filter(Country == as.character(input$Country) & year>2018 & year < 2024) %>%
  ggplot(aes(x=year, y=NGDP_R, group=Version, color = Version)) +
  geom_line()
)}
```

