---
title: "IMF WEO Dashboard by Henrique Barbosa - henriquefb@gmail.com"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
source("visualizingWEOv2.R")
countries <- unique(full_weo$Country)
```

Column {.sidebar}
-----------------------------------------------------------------------

Test

```{r}
selectInput("ctry", label = "Country",
            choices = countries, selected = "Norway")

```


Column {data-width=350}
-----------------------------------------------------------------------

### Unemployment



```{r}

renderPlot({
  
  full_weo %>% filter(Country == as.character(input$ctry) & year>2018 & year < 2024) %>% 
    ggplot(aes(y=LUR, x=year, fill=Version)) + 
    geom_bar(position="dodge", stat="identity") +
    geom_text(aes(label=LUR), vjust=1.6, color="white",
                                              position = position_dodge(0.9), size=3) +
    theme(axis.title.x=element_blank(), axis.title.y=element_blank())
    
})
```

### Fiscal


```{r}
renderPlot({
  full_weo %>% filter(Country == as.character(input$ctry) & year>2018 & year < 2024) %>% 
    ggplot(aes(y=GGXWDG_NGDP, x=year, fill=Version)) + 
    geom_bar(position="dodge", stat="identity") +
    theme(axis.title.x=element_blank(), axis.title.y=element_blank()) +
        geom_text(aes(label=GGXWDG_NGDP), vjust=1.6, color="white",
                                              position = position_dodge(0.9), size=3) +
    coord_cartesian(ylim=c(20,NA))

})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Real GDP growth

```{r}
renderPlot({
full_weo %>% filter(Country == as.character(input$ctry) & year>2018 & year < 2024) %>% 
    ggplot(aes(y=NGDP_RPCH, x=year, fill=Version)) + 
    geom_bar(position="dodge", stat="identity") +
    geom_text(aes(label=NGDP_RPCH), vjust=1.6, color="white",
                                              position = position_dodge(0.9), size=3) +
    theme(axis.title.x=element_blank(), axis.title.y=element_blank())
})
```

### Nominal GDP path

```{r}
renderPlot({
full_weo %>%
  filter(Country == as.character(input$ctry) & year>2018 & year < 2024) %>% 
    ggplot(aes(x=year, y=NGDP_R, group=Version, color = Version)) + 
    geom_line() +
    theme(axis.title.x=element_blank(), axis.title.y=element_blank())
})
```

